default:
  datafile:
    ./src/data/mystack.yml
  tpl_section:
    ./src/templates/section.pug
  tpl_icon:
    ./src/templates/icon.pug
  tag_start:
    <!-- START mystack -->
  tag_end:
    <!-- END mystack -->
  file_input:
    ./src/templates/readme.tpl.md
  file_output:
    ./build/readme.md
