name: Generate Icons

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  test_yaml:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Update packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git

      - name: Install NPM packages
        run: npm install

      - name: Test Yaml stack data
        run: npm run test:yaml

  build:
    name: Build readme.md
    needs: test_yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install NPM packages
        run: npm install

      - name: Build readme.md
        run: |
          npm run build
          cat ./build/readme.md

      # save artifact for next job
      - uses: actions/upload-artifact@v3
        with:
          name: readme-artifact
          path: ./build/readme.md

  commit_changes:
    name: Commit changes back to repo
    needs: build
    runs-on: ubuntu-latest
    steps:
        # grab previous artifact, save it in repo root
      - uses: actions/download-artifact@v3
        with:
          name: readme-artifact
          path: ./

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure git to trust the workspace despite the different owner
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Copy the name & email from the last commit
        run: |
          user_email="$(git log --format='%ae' HEAD^\!)"
          user_name="$(git log --format='%an' HEAD^\!)"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: "docs: update skills icons"
          add: "readme.md"

      - name: Display Results
        run: |
          git show --summary
